### ISSUE TITLE
Tutoriel pour le paramétrage 

### ISSUE THREAD

**Issue by FrancoFasano** [Kous92/Service-GPS-coordonnees-adresse-Android#1]
Bonjour,
J'aimerai tester cette application.
Est-elle libre de droit ?
Avez-vous rédigé un tutoriel pour le paramétrage de l'app ?
Avez-vous le modèle de données pour le côté serveur ?
Franck

**Comment by Kous92** [comment]
Bonjour,

Pour l'application, il n'y a absolument pas de soucis, vous pouvez l'utiliser et mener vos expériences avec.

Pour la partie modèle de l'architecture MVC, je n'ai pas de modèle de données. Ce sera à vous de le créer.

**Comment by FrancoFasano** [comment]
Merci pour le retour.
